### ISSUE TITLE
Export SKOS : NoMethodError : add_skos_xl_labels

### ISSUE THREAD

**Issue by pmounier** [innoq/iqvoc_skosxl#10]
Hi,

 We tried to export a SKOS vocabularie with this command line : 
rake iqvoc:export TYPE=<ttl|nt|xml> NAMESPACE='<URI>' 
and we got this error : NoMethodError: undefined method `add_skos_xl_labels'.

Can you help us ?

iqvoc_skosxl : last branch:Master 
iqvoc : Iqvoc 4.8.1

Thx.

**Comment by mjansing** [comment]
Should be fixed with iqvoc_skosxl v2.9.1.
