### ISSUE TITLE
Origins must be unique

### ISSUE THREAD

**Issue by tillsc** [innoq/iqvoc_skosxl#4]
Is there a validation for uniqueness? (I Think there is none)

What happens when a user enters a label which maps to an origin already in use? 
Example:

* Given: "Abfall&Mist" #=> origin: "Abfall-Mist"
* When the user creates a new label "Abfall-Mist" this surely is a different label. But it also maps to origin: "Abfall-Mist". There must be some kind of behaviour to allow this (e.g. an optional number at the end ["Abfall-Mist", "Abfall-Mist_2", ...])

**Comment by mjansing** [comment]
Solved some time ago with f27b1c0e48d4761966f5db1e20d802d6ce239463. Now we are using random generated hashes for origin generation.
